services:
  - type: web
    name: product-recommender
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    repo: https://github.com/Bhuvanareddy-03/hierarchical-clustering-product-recommender
    branch: main
    autoDeploy: true
