services:
  - type: web
    name: product-recommender
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    repo: Bhuvanareddy-03/Product-Recomender
    branch: main
    autoDeploy: true
